### ISSUE TITLE
Best Accuracy: 0.0

### ISSUE THREAD

**Issue by Jx-Tan** [Project-MONAI/research-contributions#19] opened 2021-10-31 04:35 UTC
**Describe the bug**
I update the trainer.py, but I still got the issues that Training Finished !, Best Accuracy: 0.0.

**To Reproduce**
1. Go to 'UNETR/BTCV'
2. Install '....'
3. Run commands 'main.py'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS
 - Python version
 - MONAI version [e.g. git commit hash]
 - CUDA/cuDNN version
 - GPU models and configuration

**Additional context**

**Comment by ahatamiz** [comment] 2021-10-31 04:58
Hi @55998 

I just tested it again with the latest version, and the issue is resolved with the latest PR #17. The final accuracy is correctly reported. 

You can also read through the code where we update the accuracy where the issue is addressed. 

Thanks

**Closed** 2021-12-01 18:37 UTC
